# This file was generated by GoReleaser. DO NOT EDIT.
cask "batlog" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "0e9d3e8f00aa103a8a34570477477d697e3589e99c62b86d28a8f58a2f64a0b0"
      url "https://github.com/jufianto/batlog/releases/download/v#{version}/batlog_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1761a49f5843c2800c7780f8b5d4c8e8b835d8bd14a61ed1ac97af421cf36686"
      url "https://github.com/jufianto/batlog/releases/download/v#{version}/batlog_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "batlog"
  desc "Record battery and per-app energy, and find out what drained it"
  homepage "https://github.com/jufianto/batlog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batlog"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/batlog"]
    end
  end

  postflight do
    if OS.mac?
      # A recorder already installed (an upgrade, or a switch from another
      # install) is re-registered on the linked binary, so it runs this version.
      if File.exist?(File.expand_path("~/Library/LaunchAgents/dev.jufi.batlog.plist"))
        system_command "#{HOMEBREW_PREFIX}/bin/batlog", args: ["daemon", "install"], print_stdout: true
      end
    end
  end
  generate_completions_from_executable "batlog",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  zap launchctl: [
      "dev.jufi.batlog",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.jufi.batlog.plist",
      "~/Library/Logs/batlog",
      "~/Library/Application Support/batlog",
    ]

  caveats <<~EOS
    Start recording (a per-user LaunchAgent, no sudo):
      batlog daemon install
    A recorder that was already installed is switched to this version automatically.
    Before `brew uninstall batlog`, run `batlog daemon uninstall` (your data is kept),
    or use `brew uninstall --zap batlog` to remove the recorder and all its data.
  EOS
end
