# This file was generated by GoReleaser. DO NOT EDIT.
cask "batlog" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5bd4f7c5c169a42a27fd0b849a37e5d2186e2384a7c1da12609b52cc9811d34c"
      url "https://github.com/jufianto/batlog/releases/download/v0.1.0/batlog_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f51dc8bbe0f363b54fa8bb4dc3475019ac1024f5ac9b795779a5091e59ecedd1"
      url "https://github.com/jufianto/batlog/releases/download/v0.1.0/batlog_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "batlog"
  desc "Record your Mac's battery and per-app energy, and find out what drained it"
  homepage "https://github.com/jufianto/batlog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batlog"

  postflight do
    if OS.mac?
      # Not notarized yet: clear the quarantine bit so Gatekeeper allows it.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/batlog"]
      # A recorder already installed (an upgrade, or a switch from another
      # install) is re-registered on the linked binary, so it runs this version.
      if File.exist?(File.expand_path("~/Library/LaunchAgents/dev.jufi.batlog.plist"))
        system_command "#{HOMEBREW_PREFIX}/bin/batlog", args: ["daemon", "install"], print_stdout: true
      end
    end
  end
  generate_completions_from_executable "batlog", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  zap launchctl: [
      "dev.jufi.batlog",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.jufi.batlog.plist",
      "~/Library/Logs/batlog",
      "~/Library/Application Support/batlog",
    ]

  caveats <<~EOS
    Start recording (a per-user LaunchAgent, no sudo):
      batlog daemon install
    A recorder that was already installed is switched to this version automatically.
    Before `brew uninstall batlog`, run `batlog daemon uninstall` (your data is kept),
    or use `brew uninstall --zap batlog` to remove the recorder and all its data.
  EOS
end
