# This file was generated by GoReleaser. DO NOT EDIT.
cask "batlog" do
  # Not notarized yet: clear the quarantine bit before anything runs the
  # binary, as generating completions does. A quarantined binary is killed
  # by Gatekeeper.
  preflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/batlog"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "aea719b8514ed40aeafa2e44a2d4e2e61e30eec324be317cb319df439f882b63"
      url "https://github.com/jufianto/batlog/releases/download/v#{version}/batlog_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "323c475dcfba00b15d0c45d85b278eefd03c827aa09ff3fe1a9d830a3c0abbec"
      url "https://github.com/jufianto/batlog/releases/download/v#{version}/batlog_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "batlog"
  desc "Record battery and per-app energy, and find out what drained it"
  homepage "https://github.com/jufianto/batlog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batlog"

  generate_completions_from_executable "batlog",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  zap launchctl: [
      "dev.jufi.batlog",
    ],
    trash: [
      "~/Library/LaunchAgents/dev.jufi.batlog.plist",
      "~/Library/Logs/batlog",
      "~/Library/Application Support/batlog",
    ]

  caveats <<~EOS
    Start recording (a per-user LaunchAgent, no sudo):
      batlog daemon install
    A recorder that was already installed switches to this version within a minute.
    Before `brew uninstall batlog`, run `batlog daemon uninstall` (your data is kept),
    or use `brew uninstall --zap batlog` to remove the recorder and all its data.
  EOS
end
